name: CI
on:
  pull_request:
    types:
    - opened
    - synchronize
  push:
    branches:
    - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: NodeJS 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: yarn
    - name: Lint
      run: |
        yarn lint
        yarn lint:ts
      env:
        CI: true

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: NodeJS 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: yarn
      - name: Test
        run: |
          cp .env.example .env
          yarn test
        env:
          CI: true

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: NodeJS 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: yarn
    - name: Build
      run: yarn build
      env:
        CI: true

  deploy:
    runs-on: ubuntu-latest
    needs: [test, build]

    steps:
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - uses: actions/checkout@v2
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Deploy image
      env:
        REGISTRY_SERVER: ${{ secrets.REGISTRY_SERVER }}
      run: ./deploy.sh
